In [127]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle 
import pandas as pd
import numpy as np

In [128]:
## Load the trained model, scaler pickle,onehot
model=load_model('model.h5')

## load the encoder and scaler
with open('label_encoder_gender.pkl','rb')as file:
    label_encoder_gender=pickle.load(file)
    
    with open('one_hot_encoder.pkl','rb')as file:
     one_hot_encoder=pickle.load(file)
    
    with open('scaler.pkl','rb')as file:
     scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [129]:
## Example input data

input_data ={
    	'CreditScore' : 200, 'Geography' : 'France'	, 'Gender' : 'Female' ,'Age' : 55,	'Tenure':1 ,	'Balance' : 150000,'NumOfProducts': 2,	'HasCrCard':1,	'IsActiveMember' : 0,	'EstimatedSalary' : 15000	}

In [130]:
geo_encoded=one_hot_encoder.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded, columns =one_hot_encoder.get_feature_names_out(['Geography']))

c:\Users\DELL\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [131]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [132]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,200,France,Female,55,1,150000,2,1,0,15000

In [133]:
## Encode categorical variables
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,200,France,0,55,1,150000,2,1,0,15000

In [134]:
## concatination one hot encoded 
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,200,0,55,1,150000,2,1,0,15000,1.0,0.0,0.0

In [135]:
## Scaling the data

input_scaled=scaler.transform(input_df)
input_scaled

array([[-4.68707758, -1.09499335,  1.53088014, -1.38944225,  1.18317786,
         0.80843615,  0.64920267, -1.02583358, -1.48536567,  1.00150113,
        -0.57946723, -0.57638802]])

In [136]:
## Predict churn

prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 259ms/step

array([[0.82918507]], dtype=float32)

In [137]:
prediction_proba=prediction[0][0]

In [138]:
prediction_proba

np.float32(0.82918507)

In [139]:
if prediction_proba>0.5:
    print('The customer is likely to churn.')
    
else:
    print('The customer is not likely to churn')

The customer is likely to churn.